@echo off

chcp 65001>nul

cd /d %~dp0

rem Получаем корневой каталог исходя из каталога запуска данного скрипта
for %%i in (%~dp0\..\..\..) do set ceredira_path=%%~fxi
rem set ceredira_path=D:\Ceredira_*.*
echo Корневой каталог: %ceredira_path%

del "%ceredira_path%\etc\install\CerediraArchiver\version\1.0.0"
del "%ceredira_path%\etc\install\CerediraArchiver\DeleteContextMenu.bat"
rem Этот файл нельзя удалять, так как выполнение скрипта прервется
rem Необходимо удалять отдельными командами из инсталлятора или вручную
rem del "%ceredira_path%\etc\install\CerediraArchiver\DeleteComponent.bat"
del "%ceredira_path%\etc\install\CerediraArchiver\CreateContextMenu.bat"
del "%ceredira_path%\bin\7-Zip\Uninstall.exe"
del "%ceredira_path%\bin\7-Zip\readme.txt"
del "%ceredira_path%\bin\7-Zip\README.md"
del "%ceredira_path%\bin\7-Zip\License.txt"
del "%ceredira_path%\bin\7-Zip\Lang\zh-tw.txt"
del "%ceredira_path%\bin\7-Zip\Lang\zh-cn.txt"
del "%ceredira_path%\bin\7-Zip\Lang\yo.txt"
del "%ceredira_path%\bin\7-Zip\Lang\vi.txt"
del "%ceredira_path%\bin\7-Zip\Lang\va.txt"
del "%ceredira_path%\bin\7-Zip\Lang\uz-cyrl.txt"
del "%ceredira_path%\bin\7-Zip\Lang\uz.txt"
del "%ceredira_path%\bin\7-Zip\Lang\uk.txt"
del "%ceredira_path%\bin\7-Zip\Lang\ug.txt"
del "%ceredira_path%\bin\7-Zip\Lang\tt.txt"
del "%ceredira_path%\bin\7-Zip\Lang\tr.txt"
del "%ceredira_path%\bin\7-Zip\Lang\tk.txt"
del "%ceredira_path%\bin\7-Zip\Lang\th.txt"
del "%ceredira_path%\bin\7-Zip\Lang\tg.txt"
del "%ceredira_path%\bin\7-Zip\Lang\ta.txt"
del "%ceredira_path%\bin\7-Zip\Lang\sw.txt"
del "%ceredira_path%\bin\7-Zip\Lang\sv.txt"
del "%ceredira_path%\bin\7-Zip\Lang\sr-spl.txt"
del "%ceredira_path%\bin\7-Zip\Lang\sr-spc.txt"
del "%ceredira_path%\bin\7-Zip\Lang\sq.txt"
del "%ceredira_path%\bin\7-Zip\Lang\sl.txt"
del "%ceredira_path%\bin\7-Zip\Lang\sk.txt"
del "%ceredira_path%\bin\7-Zip\Lang\si.txt"
del "%ceredira_path%\bin\7-Zip\Lang\sa.txt"
del "%ceredira_path%\bin\7-Zip\Lang\ru.txt"
del "%ceredira_path%\bin\7-Zip\Lang\ro.txt"
del "%ceredira_path%\bin\7-Zip\Lang\pt-br.txt"
del "%ceredira_path%\bin\7-Zip\Lang\pt.txt"
del "%ceredira_path%\bin\7-Zip\Lang\ps.txt"
del "%ceredira_path%\bin\7-Zip\Lang\pl.txt"
del "%ceredira_path%\bin\7-Zip\Lang\pa-in.txt"
del "%ceredira_path%\bin\7-Zip\Lang\nn.txt"
del "%ceredira_path%\bin\7-Zip\Lang\nl.txt"
del "%ceredira_path%\bin\7-Zip\Lang\ne.txt"
del "%ceredira_path%\bin\7-Zip\Lang\nb.txt"
del "%ceredira_path%\bin\7-Zip\Lang\ms.txt"
del "%ceredira_path%\bin\7-Zip\Lang\mr.txt"
del "%ceredira_path%\bin\7-Zip\Lang\mng2.txt"
del "%ceredira_path%\bin\7-Zip\Lang\mng.txt"
del "%ceredira_path%\bin\7-Zip\Lang\mn.txt"
del "%ceredira_path%\bin\7-Zip\Lang\mk.txt"
del "%ceredira_path%\bin\7-Zip\Lang\lv.txt"
del "%ceredira_path%\bin\7-Zip\Lang\lt.txt"
del "%ceredira_path%\bin\7-Zip\Lang\lij.txt"
del "%ceredira_path%\bin\7-Zip\Lang\ky.txt"
del "%ceredira_path%\bin\7-Zip\Lang\ku-ckb.txt"
del "%ceredira_path%\bin\7-Zip\Lang\ku.txt"
del "%ceredira_path%\bin\7-Zip\Lang\ko.txt"
del "%ceredira_path%\bin\7-Zip\Lang\kk.txt"
del "%ceredira_path%\bin\7-Zip\Lang\kab.txt"
del "%ceredira_path%\bin\7-Zip\Lang\kaa.txt"
del "%ceredira_path%\bin\7-Zip\Lang\ka.txt"
del "%ceredira_path%\bin\7-Zip\Lang\ja.txt"
del "%ceredira_path%\bin\7-Zip\Lang\it.txt"
del "%ceredira_path%\bin\7-Zip\Lang\is.txt"
del "%ceredira_path%\bin\7-Zip\Lang\io.txt"
del "%ceredira_path%\bin\7-Zip\Lang\id.txt"
del "%ceredira_path%\bin\7-Zip\Lang\hy.txt"
del "%ceredira_path%\bin\7-Zip\Lang\hu.txt"
del "%ceredira_path%\bin\7-Zip\Lang\hr.txt"
del "%ceredira_path%\bin\7-Zip\Lang\hi.txt"
del "%ceredira_path%\bin\7-Zip\Lang\he.txt"
del "%ceredira_path%\bin\7-Zip\Lang\gu.txt"
del "%ceredira_path%\bin\7-Zip\Lang\gl.txt"
del "%ceredira_path%\bin\7-Zip\Lang\ga.txt"
del "%ceredira_path%\bin\7-Zip\Lang\fy.txt"
del "%ceredira_path%\bin\7-Zip\Lang\fur.txt"
del "%ceredira_path%\bin\7-Zip\Lang\fr.txt"
del "%ceredira_path%\bin\7-Zip\Lang\fi.txt"
del "%ceredira_path%\bin\7-Zip\Lang\fa.txt"
del "%ceredira_path%\bin\7-Zip\Lang\ext.txt"
del "%ceredira_path%\bin\7-Zip\Lang\eu.txt"
del "%ceredira_path%\bin\7-Zip\Lang\et.txt"
del "%ceredira_path%\bin\7-Zip\Lang\es.txt"
del "%ceredira_path%\bin\7-Zip\Lang\eo.txt"
del "%ceredira_path%\bin\7-Zip\Lang\en.ttt"
del "%ceredira_path%\bin\7-Zip\Lang\el.txt"
del "%ceredira_path%\bin\7-Zip\Lang\de.txt"
del "%ceredira_path%\bin\7-Zip\Lang\da.txt"
del "%ceredira_path%\bin\7-Zip\Lang\cy.txt"
del "%ceredira_path%\bin\7-Zip\Lang\cs.txt"
del "%ceredira_path%\bin\7-Zip\Lang\co.txt"
del "%ceredira_path%\bin\7-Zip\Lang\ca.txt"
del "%ceredira_path%\bin\7-Zip\Lang\br.txt"
del "%ceredira_path%\bin\7-Zip\Lang\bn.txt"
del "%ceredira_path%\bin\7-Zip\Lang\bg.txt"
del "%ceredira_path%\bin\7-Zip\Lang\be.txt"
del "%ceredira_path%\bin\7-Zip\Lang\ba.txt"
del "%ceredira_path%\bin\7-Zip\Lang\az.txt"
del "%ceredira_path%\bin\7-Zip\Lang\ast.txt"
del "%ceredira_path%\bin\7-Zip\Lang\ar.txt"
del "%ceredira_path%\bin\7-Zip\Lang\an.txt"
del "%ceredira_path%\bin\7-Zip\Lang\af.txt"
del "%ceredira_path%\bin\7-Zip\History.txt"
del "%ceredira_path%\bin\7-Zip\descript.ion"
del "%ceredira_path%\bin\7-Zip\7-zip32.dll"
del "%ceredira_path%\bin\7-Zip\7-zip.dll"
del "%ceredira_path%\bin\7-Zip\7-zip.chm"
del "%ceredira_path%\bin\7-Zip\7zG.exe"
del "%ceredira_path%\bin\7-Zip\7zFM.exe"
del "%ceredira_path%\bin\7-Zip\7zCon.sfx"
del "%ceredira_path%\bin\7-Zip\7z.sfx"
del "%ceredira_path%\bin\7-Zip\7z.exe"
del "%ceredira_path%\bin\7-Zip\7z.dll"
del "%ceredira_path%\7z File Manager.bat"


rmdir "%ceredira_path%\etc\install\CerediraArchiver\version"
rem Этот каталог нельзя удалять, так как он не пустой
rem Необходимо удалять отдельными командами из инсталлятора или вручную
rem rmdir "%ceredira_path%\etc\install\CerediraArchiver"
rem rmdir "%ceredira_path%\etc\install"
rem rmdir "%ceredira_path%\etc"
rmdir "%ceredira_path%\bin\7-Zip\Lang"
rmdir "%ceredira_path%\bin\7-Zip"
rem rmdir "%ceredira_path%\bin"

pause