@echo off

chcp 65001>nul

cd /d %~dp0

rem Получаем корневой каталог исходя из каталога запуска данного скрипта
for %%i in (%~dp0\..\..\..) do set ceredira_path=%%~fxi
rem set ceredira_path=D:\Ceredira_*.*
echo Корневой каталог: %ceredira_path%

del "%ceredira_path%\WinSCP.bat"
del "%ceredira_path%\Putty.bat"
del "%ceredira_path%\PsExec.bat"
del "%ceredira_path%\mRemoteNG.bat"
del "%ceredira_path%\etc\install\CerediraRemoteAccess\version\1.0.0"
del "%ceredira_path%\etc\install\CerediraRemoteAccess\DeleteContextMenu.bat"
rem Этот файл нельзя удалять, так как выполнение скрипта прервется
rem Необходимо удалять отдельными командами из инсталлятора или вручную
rem del "%ceredira_path%\etc\install\CerediraRemoteAccess\DeleteComponent.bat"
del "%ceredira_path%\etc\install\CerediraRemoteAccess\CreateContextMenu.bat"
del "%ceredira_path%\bin\WinSCP\WinSCP.exe"
del "%ceredira_path%\bin\WinSCP\WinSCP.com"
del "%ceredira_path%\bin\WinSCP\readme.txt"
del "%ceredira_path%\bin\WinSCP\README.md"
del "%ceredira_path%\bin\WinSCP\license.txt"
del "%ceredira_path%\bin\Putty\README.md"
del "%ceredira_path%\bin\Putty\PUTTYGEN.EXE"
del "%ceredira_path%\bin\Putty\PUTTY.EXE"
del "%ceredira_path%\bin\Putty\PUTTY.CHM"
del "%ceredira_path%\bin\Putty\PSFTP.EXE"
del "%ceredira_path%\bin\Putty\PSCP.EXE"
del "%ceredira_path%\bin\Putty\PLINK.EXE"
del "%ceredira_path%\bin\Putty\PAGEANT.EXE"
del "%ceredira_path%\bin\PsExec\README.md"
del "%ceredira_path%\bin\PsExec\psversion.txt"
del "%ceredira_path%\bin\PsExec\Pstools.chm"
del "%ceredira_path%\bin\PsExec\PsExec64.exe"
del "%ceredira_path%\bin\PsExec\PsExec.exe"
del "%ceredira_path%\bin\PsExec\Eula.txt"
del "%ceredira_path%\bin\mRemoteNG\zh-TW\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\zh-CN\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\WeifenLuo.WinFormsUI.Docking.ThemeVS2015.dll"
del "%ceredira_path%\bin\mRemoteNG\WeifenLuo.WinFormsUI.Docking.ThemeVS2013.dll"
del "%ceredira_path%\bin\mRemoteNG\WeifenLuo.WinFormsUI.Docking.ThemeVS2012.dll"
del "%ceredira_path%\bin\mRemoteNG\WeifenLuo.WinFormsUI.Docking.ThemeVS2003.dll"
del "%ceredira_path%\bin\mRemoteNG\WeifenLuo.WinFormsUI.Docking.dll"
del "%ceredira_path%\bin\mRemoteNG\VncSharp.dll"
del "%ceredira_path%\bin\mRemoteNG\uk\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\tr-TR\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\Themes\vs2015light.vstheme"
del "%ceredira_path%\bin\mRemoteNG\Themes\vs2015dark.vstheme"
del "%ceredira_path%\bin\mRemoteNG\Themes\vs2015blue.vstheme"
del "%ceredira_path%\bin\mRemoteNG\Themes\darcula.vstheme"
del "%ceredira_path%\bin\mRemoteNG\Schemas\mremoteng_confcons_v2_6.xsd"
del "%ceredira_path%\bin\mRemoteNG\ru\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\Renci.SshNet.dll"
del "%ceredira_path%\bin\mRemoteNG\Readme.txt"
del "%ceredira_path%\bin\mRemoteNG\README.md"
del "%ceredira_path%\bin\mRemoteNG\PuTTYNG.exe"
del "%ceredira_path%\bin\mRemoteNG\pt-BR\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\pt\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\pl\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\ObjectListView.dll"
del "%ceredira_path%\bin\mRemoteNG\nl\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\nb-NO\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\mRemoteNG.exe.config"
del "%ceredira_path%\bin\mRemoteNG\mRemoteNG.exe"
del "%ceredira_path%\bin\mRemoteNG\MagicLibrary.dll"
del "%ceredira_path%\bin\mRemoteNG\log4net.dll"
del "%ceredira_path%\bin\mRemoteNG\ko-KR\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\ja-JP\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\it\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\Interop.WFICALib.dll"
del "%ceredira_path%\bin\mRemoteNG\Interop.MSTSCLib.dll"
del "%ceredira_path%\bin\mRemoteNG\Icons\Workstation.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Windows.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\WiFi.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Web Server.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Virtual Machine.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Test Server.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Terminal Server.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Telnet.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Tel.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Switch.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\SSH.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\SharePoint.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Router.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Remote Desktop.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\PuTTY.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\mRemoteNG.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\mRemote.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Mail Server.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Log.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Linux.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Firewall.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Finance.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\File Server.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Fax.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\ESX.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Domain Controller.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Database.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Build Server.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Backup.ico"
del "%ceredira_path%\bin\mRemoteNG\Icons\Anti Virus.ico"
del "%ceredira_path%\bin\mRemoteNG\hu\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\Help\Update.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\SSHFileTransfer.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\SQLScript.txt"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Reference\01.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Quick Connect\03.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Quick Connect\02.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Quick Connect\01.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Main Menu\View.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Main Menu\Tools.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Main Menu\QuickConnect.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Main Menu\Info.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Main Menu\File.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\External Tools\08.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\External Tools\07.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\External Tools\06.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\External Tools\05.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\External Tools\04.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\External Tools\03.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\External Tools\02.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\External Tools\01.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Configuration\17.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Configuration\16.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Configuration\15.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Configuration\14.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Configuration\13.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Configuration\12.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Configuration\11.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Configuration\10.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Configuration\09.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Configuration\08.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Configuration\07.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Configuration\06.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Configuration\05.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Configuration\04.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Configuration\03.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Configuration\02.png"
del "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Configuration\01.png"
del "%ceredira_path%\bin\mRemoteNG\Help\ScreenshotManager.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\SaveAsExport.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\QuickReference.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\QuickConnect.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\Prerequisites.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\PortScan.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\Options.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\MainMenu.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\Main.css"
del "%ceredira_path%\bin\mRemoteNG\Help\Introduction.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\Installation.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\Index.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\ImportFromAD.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\ExternalTools.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\ErrorsAndInfos.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\Connections.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\Connection.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\ConfigurationSQL.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\Configuration.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\Config.htm"
del "%ceredira_path%\bin\mRemoteNG\Help\CMDSwitches.htm"
del "%ceredira_path%\bin\mRemoteNG\Geckofx-Winforms.dll"
del "%ceredira_path%\bin\mRemoteNG\Geckofx-Core.dll"
del "%ceredira_path%\bin\mRemoteNG\fr\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\Firefox\xul.dll"
del "%ceredira_path%\bin\mRemoteNG\Firefox\softokn3.dll"
del "%ceredira_path%\bin\mRemoteNG\Firefox\sandboxbroker.dll"
del "%ceredira_path%\bin\mRemoteNG\Firefox\plugin-hang-ui.exe"
del "%ceredira_path%\bin\mRemoteNG\Firefox\plugin-container.exe"
del "%ceredira_path%\bin\mRemoteNG\Firefox\omni.ja"
del "%ceredira_path%\bin\mRemoteNG\Firefox\nssdbm3.dll"
del "%ceredira_path%\bin\mRemoteNG\Firefox\nssckbi.dll"
del "%ceredira_path%\bin\mRemoteNG\Firefox\nss3.dll"
del "%ceredira_path%\bin\mRemoteNG\Firefox\mozglue.dll"
del "%ceredira_path%\bin\mRemoteNG\Firefox\libGLESv2.dll"
del "%ceredira_path%\bin\mRemoteNG\Firefox\libEGL.dll"
del "%ceredira_path%\bin\mRemoteNG\Firefox\lgpllibs.dll"
del "%ceredira_path%\bin\mRemoteNG\Firefox\icuuc56.dll"
del "%ceredira_path%\bin\mRemoteNG\Firefox\icuin56.dll"
del "%ceredira_path%\bin\mRemoteNG\Firefox\icudt56.dll"
del "%ceredira_path%\bin\mRemoteNG\Firefox\freebl3.dll"
del "%ceredira_path%\bin\mRemoteNG\Firefox\d3dcompiler_47.dll"
del "%ceredira_path%\bin\mRemoteNG\Firefox\breakpadinjector.dll"
del "%ceredira_path%\bin\mRemoteNG\Firefox\AccessibleMarshal.dll"
del "%ceredira_path%\bin\mRemoteNG\es-AR\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\es\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\en-US\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\el\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\de\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\cs-CZ\mRemoteNG.resources.dll"
del "%ceredira_path%\bin\mRemoteNG\CREDITS.TXT"
del "%ceredira_path%\bin\mRemoteNG\COPYING.TXT"
del "%ceredira_path%\bin\mRemoteNG\CHANGELOG.TXT"
del "%ceredira_path%\bin\mRemoteNG\BouncyCastle.Crypto.dll"
del "%ceredira_path%\bin\mRemoteNG\AxInterop.WFICALib.dll"
del "%ceredira_path%\bin\mRemoteNG\AxInterop.MSTSCLib.dll"
del "%ceredira_path%\bin\mRemoteNG\ADTree.dll"

rmdir "%ceredira_path%\etc\install\CerediraRemoteAccess\version"
rem Этот каталог нельзя удалять, так как он не пустой
rem Необходимо удалять отдельными командами из инсталлятора или вручную
rem rmdir "%ceredira_path%\etc\install\CerediraRemoteAccess"
rem rmdir "%ceredira_path%\etc\install"
rem rmdir "%ceredira_path%\etc"
rmdir "%ceredira_path%\bin\WinSCP"
rmdir "%ceredira_path%\bin\Putty"
rmdir "%ceredira_path%\bin\PsExec"
rmdir "%ceredira_path%\bin\mRemoteNG\zh-TW"
rmdir "%ceredira_path%\bin\mRemoteNG\zh-CN"
rmdir "%ceredira_path%\bin\mRemoteNG\uk"
rmdir "%ceredira_path%\bin\mRemoteNG\tr-TR"
rmdir "%ceredira_path%\bin\mRemoteNG\Themes"
rmdir "%ceredira_path%\bin\mRemoteNG\Schemas"
rmdir "%ceredira_path%\bin\mRemoteNG\ru"
rmdir "%ceredira_path%\bin\mRemoteNG\pt-BR"
rmdir "%ceredira_path%\bin\mRemoteNG\pt"
rmdir "%ceredira_path%\bin\mRemoteNG\pl"
rmdir "%ceredira_path%\bin\mRemoteNG\nl"
rmdir "%ceredira_path%\bin\mRemoteNG\nb-NO"
rmdir "%ceredira_path%\bin\mRemoteNG\ko-KR"
rmdir "%ceredira_path%\bin\mRemoteNG\ja-JP"
rmdir "%ceredira_path%\bin\mRemoteNG\it"
rmdir "%ceredira_path%\bin\mRemoteNG\Icons"
rmdir "%ceredira_path%\bin\mRemoteNG\hu"
rmdir "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Reference"
rmdir "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Quick Connect"
rmdir "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Main Menu"
rmdir "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\External Tools"
rmdir "%ceredira_path%\bin\mRemoteNG\Help\Screenshots\Configuration"
rmdir "%ceredira_path%\bin\mRemoteNG\Help\Screenshots"
rmdir "%ceredira_path%\bin\mRemoteNG\Help"
rmdir "%ceredira_path%\bin\mRemoteNG\fr"
rmdir "%ceredira_path%\bin\mRemoteNG\Firefox"
rmdir "%ceredira_path%\bin\mRemoteNG\es-AR"
rmdir "%ceredira_path%\bin\mRemoteNG\es"
rmdir "%ceredira_path%\bin\mRemoteNG\en-US"
rmdir "%ceredira_path%\bin\mRemoteNG\el"
rmdir "%ceredira_path%\bin\mRemoteNG\de"
rmdir "%ceredira_path%\bin\mRemoteNG\cs-CZ"
rmdir "%ceredira_path%\bin\mRemoteNG"
rem rmdir "%ceredira_path%\bin"

pause