@echo off

chcp 65001>nul

cd /d %~dp0

rem Получаем корневой каталог исходя из каталога запуска данного скрипта
for %%i in (%~dp0\..\..\..) do set ceredira_path=%%~fxi
rem set ceredira_path=D:\Ceredira_*.*
echo Корневой каталог: %ceredira_path%

del "%ceredira_path%\Scanner.bat"
del "%ceredira_path%\PsTools.bat"
del "%ceredira_path%\Nssm.bat"
del "%ceredira_path%\MultiCommander.bat"
del "%ceredira_path%\man\CerediraAdministration\README.md"
del "%ceredira_path%\LdapAdmin.bat"
del "%ceredira_path%\etc\install\CerediraAdministration\version\1.1.0"
del "%ceredira_path%\etc\install\CerediraAdministration\DeleteContextMenu.bat"
rem Этот файл нельзя удалять, так как выполнение скрипта прервется
rem Необходимо удалять отдельными командами из инсталлятора или вручную
rem del "%ceredira_path%\etc\install\CerediraAdministration\DeleteComponent.bat"
del "%ceredira_path%\etc\install\CerediraAdministration\CreateContextMenu.bat"
del "%ceredira_path%\bin\Scanner\Scanner.lang"
del "%ceredira_path%\bin\Scanner\Scanner.exe"
del "%ceredira_path%\bin\Scanner\Scanner.en.txt"
del "%ceredira_path%\bin\Scanner\Scanner.de.txt"
del "%ceredira_path%\bin\Scanner\README.md"
del "%ceredira_path%\bin\Scanner\Delete Scanner from Context Menu.reg"
del "%ceredira_path%\bin\Scanner\Add Scanner to Context Menu.reg"
del "%ceredira_path%\bin\PsTools\README.md"
del "%ceredira_path%\bin\PsTools\psversion.txt"
del "%ceredira_path%\bin\PsTools\Pstools.chm"
del "%ceredira_path%\bin\PsTools\pssuspend64.exe"
del "%ceredira_path%\bin\PsTools\pssuspend.exe"
del "%ceredira_path%\bin\PsTools\psshutdown64.exe"
del "%ceredira_path%\bin\PsTools\psshutdown.exe"
del "%ceredira_path%\bin\PsTools\PsService64.exe"
del "%ceredira_path%\bin\PsTools\PsService.exe"
del "%ceredira_path%\bin\PsTools\psping64.exe"
del "%ceredira_path%\bin\PsTools\psping.exe"
del "%ceredira_path%\bin\PsTools\pspasswd64.exe"
del "%ceredira_path%\bin\PsTools\pspasswd.exe"
del "%ceredira_path%\bin\PsTools\psloglist64.exe"
del "%ceredira_path%\bin\PsTools\psloglist.exe"
del "%ceredira_path%\bin\PsTools\PsLoggedon64.exe"
del "%ceredira_path%\bin\PsTools\PsLoggedon.exe"
del "%ceredira_path%\bin\PsTools\pslist64.exe"
del "%ceredira_path%\bin\PsTools\pslist.exe"
del "%ceredira_path%\bin\PsTools\pskill64.exe"
del "%ceredira_path%\bin\PsTools\pskill.exe"
del "%ceredira_path%\bin\PsTools\PsInfo64.exe"
del "%ceredira_path%\bin\PsTools\PsInfo.exe"
del "%ceredira_path%\bin\PsTools\PsGetsid64.exe"
del "%ceredira_path%\bin\PsTools\PsGetsid.exe"
del "%ceredira_path%\bin\PsTools\psfile64.exe"
del "%ceredira_path%\bin\PsTools\psfile.exe"
del "%ceredira_path%\bin\PsTools\PsExec64.exe"
del "%ceredira_path%\bin\PsTools\PsExec.exe"
del "%ceredira_path%\bin\PsTools\Eula.txt"
del "%ceredira_path%\bin\Nssm\README.md"
del "%ceredira_path%\bin\Nssm\nssm.exe"
del "%ceredira_path%\bin\MultiCommander\USBStart.dat"
del "%ceredira_path%\bin\MultiCommander\SessionConfig\Config\MultiCommander.ini"
del "%ceredira_path%\bin\MultiCommander\README.md"
del "%ceredira_path%\bin\MultiCommander\MultiUpdate.exe"
del "%ceredira_path%\bin\MultiCommander\MultiCrashReport.exe"
del "%ceredira_path%\bin\MultiCommander\MultiCommander.exe"
del "%ceredira_path%\bin\MultiCommander\MCIcons.dll"
del "%ceredira_path%\bin\MultiCommander\MCAdmin.exe"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_uk.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_tw.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_tr.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_sl-SI.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_se.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_ru.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_ro.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_pt-BR.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_pt.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_pl.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_no.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_nl.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_lt.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_ko.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_jp.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_it.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_hu.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_fr.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_es.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_en.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_de.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_cz.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_cn.zip"
del "%ceredira_path%\bin\MultiCommander\Languages\MC_LangPack_bg.zip"
del "%ceredira_path%\bin\MultiCommander\Extensions\MultiFileViewer\MultiFileViewer.xml"
del "%ceredira_path%\bin\MultiCommander\Extensions\MultiFileViewer\MultiFileViewer.dll"
del "%ceredira_path%\bin\MultiCommander\Extensions\MultiFileViewer\ColorFormatting.xml"
del "%ceredira_path%\bin\MultiCommander\Extensions\MFTools\MFTools.dll"
del "%ceredira_path%\bin\MultiCommander\Extensions\MCVideoTools\MCVideoTools.dll"
del "%ceredira_path%\bin\MultiCommander\Extensions\MCUtils\MCUtils.dll"
del "%ceredira_path%\bin\MultiCommander\Extensions\MCSpecial\MCSpecial.dll"
del "%ceredira_path%\bin\MultiCommander\Extensions\MCPictureTools\MCPictureTools.dll"
del "%ceredira_path%\bin\MultiCommander\Extensions\MCPictureTools\ExifWin.dll"
del "%ceredira_path%\bin\MultiCommander\Extensions\MCLanEditor\MCLanEditor.dll"
del "%ceredira_path%\bin\MultiCommander\Extensions\MCAudioTools\MCAudioTools.dll"
del "%ceredira_path%\bin\MultiCommander\Extensions\FSRegistry\FSRegistry.dll"
del "%ceredira_path%\bin\MultiCommander\Extensions\FSRAR\FSRAR.dll"
del "%ceredira_path%\bin\MultiCommander\Extensions\FSPortable\FSPortable_def.xml"
del "%ceredira_path%\bin\MultiCommander\Extensions\FSPortable\FSPortable.xml"
del "%ceredira_path%\bin\MultiCommander\Extensions\FSPortable\FSPortable.dll"
del "%ceredira_path%\bin\MultiCommander\Extensions\FSFTP\FSFTP.xml"
del "%ceredira_path%\bin\MultiCommander\Extensions\FSFTP\FSFTP.dll"
del "%ceredira_path%\bin\MultiCommander\Extensions\FS7Zip\FS7Zip.dll"
del "%ceredira_path%\bin\MultiCommander\Extensions\FS7Zip\7za_x64.dll"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\viewfilter.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\totd.xml"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\tab.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\syncview.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\saveclip.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\refresh.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\quicksetup.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\prop.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\pathrow.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\mkdir.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\loadsavesel.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\history.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\gotoroot.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\fullwidth.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\fsreg.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\foldersize.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\findopenfiles.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\explorersetup.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\expandsel.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\disconnect.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\devsel.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\deletefilter.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\custkeys.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\copyplugins.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\copypath.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\copymovefilter.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\convertcrlf.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\compareviews.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\checksum.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\change_case.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\btnpanel.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\btneditor.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\backup.png"
del "%ceredira_path%\bin\MultiCommander\Config\TOTD\back.png"
del "%ceredira_path%\bin\MultiCommander\Config\SupportedLanguages.xml"
del "%ceredira_path%\bin\MultiCommander\Config\Scripts\Examples\Examples.zip"
del "%ceredira_path%\bin\MultiCommander\Config\Presets\ExplorerPanel\Style - Explorer.xml"
del "%ceredira_path%\bin\MultiCommander\Config\Presets\ExplorerPanel\Style - Commander Clone.xml"
del "%ceredira_path%\bin\MultiCommander\Config\Presets\ExplorerPanel\Colors and Style - Explorer.xml"
del "%ceredira_path%\bin\MultiCommander\Config\Presets\ExplorerPanel\Colors and Style - Default.xml"
del "%ceredira_path%\bin\MultiCommander\Config\Presets\ExplorerPanel\Colors - White.xml"
del "%ceredira_path%\bin\MultiCommander\Config\Presets\ExplorerPanel\Colors - Explorer.xml"
del "%ceredira_path%\bin\MultiCommander\Config\Presets\ExplorerPanel\Colors - Black.xml"
del "%ceredira_path%\bin\MultiCommander\Config\MultiCrashReport.ini"
del "%ceredira_path%\bin\MultiCommander\Config\MultiCommander_def.xml"
del "%ceredira_path%\bin\MultiCommander\Config\MultiCommander.xml"
del "%ceredira_path%\bin\MultiCommander\Config\MultiButtons.xml"
del "%ceredira_path%\bin\MultiCommander\Config\Modules.xml"
del "%ceredira_path%\bin\MultiCommander\Config\FSZip_def.xml"
del "%ceredira_path%\bin\MultiCommander\Config\FSZip.xml"
del "%ceredira_path%\bin\MultiCommander\Config\FSLocal_def.xml"
del "%ceredira_path%\bin\MultiCommander\Config\FileOpPluginProfiles.xml"
del "%ceredira_path%\bin\MultiCommander\Config\ExplorerPanel_def.xml"
del "%ceredira_path%\bin\MultiCommander\Config\ExplorerPanel.xml"
del "%ceredira_path%\bin\MultiCommander\Config\DataPreviewTemplates_tpl.xml"
del "%ceredira_path%\bin\MultiCommander\Config\ConfigProfiles.xml"
del "%ceredira_path%\bin\MultiCommander\Config\ColorRules\ColorsRules_DarkMode.xml"
del "%ceredira_path%\bin\MultiCommander\Config\ColorRules.xml"
del "%ceredira_path%\bin\MultiCommander\Config\ColorRules.tpl"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\WindowsExplorer-Overall-ExplorerPanel.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\WindowsExplorer-Mouse-ExplorerPanel.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\WindowsExplorer-Keyboard-ExplorerPanel.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\WindowsExplorer-Keyboard-CustomKeymappings.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\WindowsExplorer-Color-MultiCommander.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\WindowsExplorer-Color-ExplorerPanel.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\WindowsExplorer-ColorDarkMode-MultiCommander.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\WindowsExplorer-ColorDarkMode-ExplorerPanel.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\CommanderStyle-Overall-ExplorerPanel.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\CommanderStyle-Mouse-ExplorerPanel.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\CommanderStyle-Keyboard-ExplorerPanel.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\CommanderStyle-Keyboard-CustomKeymappings.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\CommanderStyle-Dark-MultiCommander.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\CommanderStyle-Dark-ExplorerPanel.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\CommanderStyle-ColorNC-MultiCommander.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\CommanderStyle-ColorNC-ExplorerPanel.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\CommanderStyle-Color-MultiCommander.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\CommanderStyle-Color-ExplorerPanel.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\CommanderStyle-ColorDarkMode-MultiCommander.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\CommanderStyle-ColorDarkMode-ExplorerPanel.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\CommanderStyle-ColorAlternating-MultiCommander.xml"
del "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles\CommanderStyle-ColorAlternating-ExplorerPanel.xml"
del "%ceredira_path%\bin\MultiCommander\Config\Aliases.xml"
del "%ceredira_path%\bin\MultiCommander\ChangeLog.txt"
del "%ceredira_path%\bin\LdapAdmin\README.md"
del "%ceredira_path%\bin\LdapAdmin\LdapAdmin.exe"


rmdir "%ceredira_path%\man\CerediraAdministration"
rmdir "%ceredira_path%\man"
rmdir "%ceredira_path%\etc\install\CerediraAdministration\version"
rem Этот каталог нельзя удалять, так как он не пустой
rem Необходимо удалять отдельными командами из инсталлятора или вручную
rem rmdir "%ceredira_path%\etc\install\CerediraAdministration"
rem rmdir "%ceredira_path%\etc\install"
rem rmdir "%ceredira_path%\etc"
rmdir "%ceredira_path%\bin\Scanner"
rmdir "%ceredira_path%\bin\PsTools"
rmdir "%ceredira_path%\bin\Nssm"
rmdir "%ceredira_path%\bin\MultiCommander\SessionConfig\Config"
rmdir "%ceredira_path%\bin\MultiCommander\SessionConfig"
rmdir "%ceredira_path%\bin\MultiCommander\Languages"
rmdir "%ceredira_path%\bin\MultiCommander\Extensions\MultiFileViewer"
rmdir "%ceredira_path%\bin\MultiCommander\Extensions\MFTools"
rmdir "%ceredira_path%\bin\MultiCommander\Extensions\MCVideoTools"
rmdir "%ceredira_path%\bin\MultiCommander\Extensions\MCUtils"
rmdir "%ceredira_path%\bin\MultiCommander\Extensions\MCSpecial"
rmdir "%ceredira_path%\bin\MultiCommander\Extensions\MCPictureTools"
rmdir "%ceredira_path%\bin\MultiCommander\Extensions\MCLanEditor"
rmdir "%ceredira_path%\bin\MultiCommander\Extensions\MCAudioTools"
rmdir "%ceredira_path%\bin\MultiCommander\Extensions\FSRegistry"
rmdir "%ceredira_path%\bin\MultiCommander\Extensions\FSRAR"
rmdir "%ceredira_path%\bin\MultiCommander\Extensions\FSPortable"
rmdir "%ceredira_path%\bin\MultiCommander\Extensions\FSFTP"
rmdir "%ceredira_path%\bin\MultiCommander\Extensions\FS7Zip"
rmdir "%ceredira_path%\bin\MultiCommander\Extensions"
rmdir "%ceredira_path%\bin\MultiCommander\Config\TOTD"
rmdir "%ceredira_path%\bin\MultiCommander\Config\Scripts\Examples"
rmdir "%ceredira_path%\bin\MultiCommander\Config\Scripts"
rmdir "%ceredira_path%\bin\MultiCommander\Config\Presets\ExplorerPanel"
rmdir "%ceredira_path%\bin\MultiCommander\Config\Presets"
rmdir "%ceredira_path%\bin\MultiCommander\Config\ColorRules"
rmdir "%ceredira_path%\bin\MultiCommander\Config\CfgProfiles"
rmdir "%ceredira_path%\bin\MultiCommander\Config"
rmdir "%ceredira_path%\bin\MultiCommander"
rmdir "%ceredira_path%\bin\LdapAdmin"
rem rmdir "%ceredira_path%\bin"

pause